import Head from 'next/head'
import Image from 'next/image'
import Feed from '../components/Feed'
import Header from '../components/Header'
import Nav from '../components/Nav'
import request from '../utils/request'

export default function Home({results}) {

  return (
    <div >
      <Head>
        <title>YOLO</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Nav />
      <Feed results={results}/>
      <div className='mt-5 bg-gray-400 p-3 text-white'>
        <span className='font-bold text-lg'>&copy; 2022 Ghis</span>
      </div>
    </div>
  )
}

export async function getServerSideProps(context){
  const genre=context.query.genre
  const requests= await fetch(`https://api.themoviedb.org/3${request[genre]?.url ||  request.fetchTrending.url}`)
      .then(res=>res.json())
  return {
    props:{
       results:requests.results
    }
  }
}